// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6Y_Fr5inQXJ1ETVN7qg2e4iOJrSP_2U',
    appId: '1:417080647213:web:fa96ba0cb2cdf272fa62a4',
    messagingSenderId: '417080647213',
    projectId: 'skincare-stack',
    authDomain: 'skincare-stack.firebaseapp.com',
    storageBucket: 'skincare-stack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRv_WP9-kP6ewZopYB9EBhwzsauTjmlU',
    appId: '1:417080647213:android:2e2f37221341bf38fa62a4',
    messagingSenderId: '417080647213',
    projectId: 'skincare-stack',
    storageBucket: 'skincare-stack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMJudz3Vw98Ck5kAIX0nzAA8pmRdSC_I',
    appId: '1:417080647213:ios:47fade377b2f4a51fa62a4',
    messagingSenderId: '417080647213',
    projectId: 'skincare-stack',
    storageBucket: 'skincare-stack.firebasestorage.app',
    iosBundleId: 'com.example.skincareStack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMJudz3Vw98Ck5kAIX0nzAA8pmRdSC_I',
    appId: '1:417080647213:ios:47fade377b2f4a51fa62a4',
    messagingSenderId: '417080647213',
    projectId: 'skincare-stack',
    storageBucket: 'skincare-stack.firebasestorage.app',
    iosBundleId: 'com.example.skincareStack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa6Y_Fr5inQXJ1ETVN7qg2e4iOJrSP_2U',
    appId: '1:417080647213:web:a39e2c6db1dd3c3ffa62a4',
    messagingSenderId: '417080647213',
    projectId: 'skincare-stack',
    authDomain: 'skincare-stack.firebaseapp.com',
    storageBucket: 'skincare-stack.firebasestorage.app',
  );
}
